/**
 * Unit tests for getUserById — generated by unit-test-generator agent
 * Bug: API-404 — GET /api/users/:id returns 404 for valid user IDs
 * Covers only changed code per fix-summary.md
 */

const { getUserById } = require('../src/controllers/userController');

// Helper: create mock Express req/res objects
function mockReq(id) {
  return { params: { id } };
}

function mockRes() {
  const res = {};
  res.status = jest.fn().mockReturnValue(res);
  res.json = jest.fn().mockReturnValue(res);
  return res;
}

describe('getUserById', () => {
  test('returns user object with 200 when numeric ID matches', async () => {
    const req = mockReq('123');
    const res = mockRes();

    await getUserById(req, res);

    expect(res.status).not.toHaveBeenCalled();
    expect(res.json).toHaveBeenCalledWith({
      id: 123,
      name: 'Alice Smith',
      email: 'alice@example.com'
    });
  });

  test('returns 404 when user ID does not exist', async () => {
    const req = mockReq('999');
    const res = mockRes();

    await getUserById(req, res);

    expect(res.status).toHaveBeenCalledWith(404);
    expect(res.json).toHaveBeenCalledWith({ error: 'User not found' });
  });

  test('REGRESSION: string "123" now correctly finds user (before fix this would 404)', async () => {
    // Before fix: parseInt was not called, "123" !== 123 → always 404
    // After fix:  parseInt("123", 10) === 123 → finds user
    const req = mockReq('123');
    const res = mockRes();

    await getUserById(req, res);

    expect(res.json).toHaveBeenCalledWith(expect.objectContaining({ id: 123 }));
    expect(res.status).not.toHaveBeenCalledWith(404);
  });

  test('returns 400 for non-numeric string ID', async () => {
    const req = mockReq('abc');
    const res = mockRes();

    await getUserById(req, res);

    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({ error: 'Invalid user ID' });
  });

  test('returns 400 for empty string ID', async () => {
    const req = mockReq('');
    const res = mockRes();

    await getUserById(req, res);

    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({ error: 'Invalid user ID' });
  });
});
